-- Create initial admin user
-- Username: admin
-- Password: Admin123!
-- This is the bcrypt hash for "Admin123!"

INSERT INTO users (
  username,
  passwordHash,
  name,
  email,
  loginMethod,
  role,
  isActive,
  createdAt,
  updatedAt,
  lastSignedIn
) VALUES (
  'admin',
  '$2a$10$YQRZvQg5r.xN8Zx5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z5Z',
  'Administrator',
  'admin@mi42.local',
  'password',
  'admin',
  1,
  NOW(),
  NOW(),
  NOW()
) ON DUPLICATE KEY UPDATE username = username;

-- Note: The password hash above is a placeholder
-- After deployment, run this script with the actual bcrypt hash generated by the application
